services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=${ENV}

  nginx-proxy:
    image: nginx:1.27
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt/live 
      - ./nginx/html:/var/www/html         

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html --deploy-hook 'nginx -s reload'; sleep 12h & wait $${!}; done"
