
services:

  nginx-proxy:
    image: nginx:1.27
    container_name: nginx-proxy
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.2in1.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - web
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html; sleep 12h & wait $${!}; done"


networks:
  web: 
    external: true